// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChUJSaHa6-jmvxpmR6-RZJc9a5lmqnSk8',
    appId: '1:136703926561:web:d4029af52339cdd0f61e60',
    messagingSenderId: '136703926561',
    projectId: 'personalassetmanager-5aa18',
    authDomain: 'personalassetmanager-5aa18.firebaseapp.com',
    storageBucket: 'personalassetmanager-5aa18.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnXdVHQptlujHEv0z7WlwUouaxhteN2z8',
    appId: '1:136703926561:ios:fe58f89eb14aa690f61e60',
    messagingSenderId: '136703926561',
    projectId: 'personalassetmanager-5aa18',
    storageBucket: 'personalassetmanager-5aa18.appspot.com',
    androidClientId: '136703926561-i98o260steh46gnc4vc70cuhdpdv4iof.apps.googleusercontent.com',
    iosClientId: '136703926561-1r38ahhqehktffu4d98ebhsf7ihb02lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChUJSaHa6-jmvxpmR6-RZJc9a5lmqnSk8',
    appId: '1:136703926561:web:a03bf0121a116eb5f61e60',
    messagingSenderId: '136703926561',
    projectId: 'personalassetmanager-5aa18',
    authDomain: 'personalassetmanager-5aa18.firebaseapp.com',
    storageBucket: 'personalassetmanager-5aa18.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnXdVHQptlujHEv0z7WlwUouaxhteN2z8',
    appId: '1:136703926561:ios:fe58f89eb14aa690f61e60',
    messagingSenderId: '136703926561',
    projectId: 'personalassetmanager-5aa18',
    storageBucket: 'personalassetmanager-5aa18.appspot.com',
    androidClientId: '136703926561-i98o260steh46gnc4vc70cuhdpdv4iof.apps.googleusercontent.com',
    iosClientId: '136703926561-1r38ahhqehktffu4d98ebhsf7ihb02lk.apps.googleusercontent.com',
    iosBundleId: 'com.example.pamApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC76NRqUJBZDEO1Id0w4ZVrceY5r4pmOZs',
    appId: '1:136703926561:android:1581c27f9323a944f61e60',
    messagingSenderId: '136703926561',
    projectId: 'personalassetmanager-5aa18',
    storageBucket: 'personalassetmanager-5aa18.appspot.com',
  );

}